version: 2.1

# Jobs

jobs:
  build_node18:
    docker:
      - image: cimg/node:19.8.0
    steps:
      - checkout
      - run: yarn install --immutable --immutable-cache
      - run: yarn run lint:prettier

# Workflows

workflows:
  version: 2

  main-workflow:
    jobs:
      - build_node18:
          filters:
            tags:
              only: /.*/
