version: 2.1

# Jobs

jobs:
  checkout:
    docker:
      - image: circleci/node:17
    steps:
      - checkout

# Workflows

workflows:
  version: 2

  main-workflow:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
