version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

workflows:
  version: 2

  main-workflow:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
